services:
  imuviewer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=tracker.moncef.studio
      - LETSENCRYPT_HOST=tracker.moncef.studio
      - LETSENCRYPT_EMAIL=moncef.hassani03@gmail.com

networks:
  default:
    external:
      name: nginx-proxy